<?php
echo $this->headScript()->appendScript(
    'function modalAlert(type, text, confirmCallback, hideCallback){
    if(!type) {
        return false;
    }
    var $modal = $(".alertModal_' . $id . '." + type);
    if (text) {
        $modal.find(\'.panel-body\').html(text);
    }
    if (confirmCallback) {
        $modal.data(\'confirm\', confirmCallback);
    }
    if (hideCallback) {
        $modal.data(\'hide\', hideCallback);
    }
    $modal.modal(\'show\')
};

$(document).ready(function(){
    $(\'.confirm_' . $id . '\').on(\'click\', function(e){
        var $modal = $(".alertModal_' . $id . '"),
            callback = $modal.data(\'confirm\');
        if(typeof callback === \'function\') {
            callback($modal);
        }
    });
    $(".alertModal_' . $id . '").on(\'hide\', function(e){
        var $modal = $(e.currentTarget),
            callback = $modal.data(\'hide\');
        if(typeof callback === \'function\') {
            callback($modal);
        }
        $modal
            .data(\'hide\', null)
            .data(\'confirm\', null)
            .data(\'cancel\', null);
    });
});');
?>

<?php foreach ($availableClasses as $class): ?>

    <div class="alertModal_<?php echo $id . ' ' . $class ?> modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="panel panel-<?php echo $class ?> panel-alt">
                    <div class="panel-heading">
                        <div class="panel-btns">
                            <a data-dismiss="modal" aria-hidden="true">&times;</a>
                        </div>
                        <!-- panel-btns -->
                        <h3 class="panel-title"></h3>
                    </div>
                    <div class="panel-body">
                    </div>
                    <div class="panel-footer">
                        <button class="btn btn-primary btn-<?php echo $class ?> confirm_<?php echo $id ?>"
                                data-dismiss="modal" aria-hidden="true">Ok
                        </button>
                    </div>
                </div>

            </div>
        </div>
    </div>

<?php endforeach; ?>